emigrant/Controllers/EmigrantesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using emigrant.Data;
using emigrant.Models;
using emigrantContext = emigrant.Data.emigrantContext;

namespace emigrant.Controllers
{
    public class EmigrantesController : Controller
    {
        private emigrantContext db = new emigrantContext();

        // GET: Emigrantes
        public ActionResult Index()
        {
            return View(db.Emigrantes.ToList());
        }

        // GET: Emigrantes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Emigrante emigrante = db.Emigrantes.Find(id);
            if (emigrante == null)
            {
                return HttpNotFound();
            }
            return View(emigrante);
        }

        // GET: Emigrantes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Emigrantes/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,nombre,apellidos,tipoIdentificacion,numeroIdentificacion,pais,fechaNacimiento,correoElectronico,numeroTelefonico,direccionActual,ciudad,situacionLaboral")] Emigrante emigrante)
        {
            if (ModelState.IsValid)
            {   
                

                db.Emigrantes.Add(emigrante);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            

            return View(emigrante);
        }

        // GET: Emigrantes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Emigrante emigrante = db.Emigrantes.Find(id);
            if (emigrante == null)
            {
                return HttpNotFound();
            }
            return View(emigrante);
        }

        // POST: Emigrantes/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,nombre,apellidos,tipoIdentificacion,numeroIdentificacion,pais,fechaNacimiento,correoElectronico,numeroTelefonico,direccionActual,ciudad,situacionLaboral")] Emigrante emigrante)
        {
            if (ModelState.IsValid)
            {
                db.Entry(emigrante).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(emigrante);
        }

        // GET: Emigrantes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Emigrante emigrante = db.Emigrantes.Find(id);
            if (emigrante == null)
            {
                return HttpNotFound();
            }
            return View(emigrante);
        }

        // POST: Emigrantes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Emigrante emigrante = db.Emigrantes.Find(id);
            db.Emigrantes.Remove(emigrante);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        //Consulta de Base de datos
        List<DNI> ListDNI() { 
            List<DNI> DNI = new List<DNI>();
            return DNI;
        }


       


    }
}

emigrant/Views/Shared/LayautGerencial.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Imagrant</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.js" />
    <script src="~/Scripts/jquery-3.4.1.js" />
    <link href="~/Content/jquery.dataTables.css" rel="stylesheet" />
    <script src="~/Scripts/jquery.dataTables.js " />

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <div class="container">
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Gerencia Emigrantes", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
        


                    </ul>
                </div>
            </div>
        </div>
    </div>
    <br />
    <br /><br />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Hacktaton MinTIC</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

emigrant/Views/Shared/LayoutAdmni.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Imagrant</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <div class="container">
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Gerencia Emigrantes App", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Inicio", "Index", "Home")</li>



                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Hacktaton MinTIC</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

emigrant/Views/Shared/View.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Imagrant</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.js" />
    <script src="~/Scripts/jquery-3.4.1.js" />
    <link href="~/Content/jquery.dataTables.css" rel="stylesheet" />
    <script src="~/Scripts/jquery.dataTables.js " />

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <div class="container">
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Novedades Emigrantes App", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Inicio", "Index", "Home")</li>


                    </ul>
                </div>
            </div>
        </div>
    </div>
    <br />
    <br /><br />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Hacktaton MinTIC</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

emigrant/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Imagrant</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet"/>
    <script src="~/Scripts/bootstrap.js"/>
    <script src="~/Scripts/jquery-3.4.1.js"/>
    <link href="~/Content/jquery.dataTables.css" rel="stylesheet"/> 
    <script src="~/Scripts/jquery.dataTables.js "/>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <div class="container">
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Emigrantes App", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                        <li>@Html.ActionLink("Registro Emigrantes", "Create", "Emigrantes")</li>
                        <li>@Html.ActionLink("Consultar Informacion", "Index", "Emigrantes")</li>
						<li>@Html.ActionLink("Servicios", "Index", "Servicios")</li>
						<li>@Html.ActionLink("Emergencias", "Index", "Emergencias")</li>
                        <li>@Html.ActionLink("Consultar ", "Consulta", "Emigrantes")</li>


                    </ul>
                </div>
            </div>
        </div>
    </div>
    <br />
    <br /><br />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Hacktaton MinTIC</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>